service: hello-world

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  stage: ${env:NODE_ENV, 'dev'}
  environment:
    AWS_REGION: ''

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${self:provider.stage}-authentication-users"
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1